### ISSUE TITLE
Add more complete examples

### ISSUE THREAD

**Issue by tpgillam** [tpgillam/mt2#13]
We should add a few more examples, ideally with a nice plot or two, demonstrating broadcasting.

**Comment by tpgillam** [comment]
@kesterlester do you have any thoughts on the kinds of plots that might be interesting? I was thinking maybe a 2d plot, with MT2 represented as colour, and then varying two other things... but what two things would work best in your opinion? 

[I can easily try a few things]

**Comment by kesterlester** [comment]
Most common plots people like to see for MT2 would either be 

(a) histograms over (say) WW - lnulnu events showing it stopping at 81GeV, or

(b) plots like these:
![image](https://user-images.githubusercontent.com/2091838/107589423-de92e980-6bfd-11eb-8731-da7ba8b2f4d7.png)

from https://arxiv.org/pdf/0711.4008.pdf

**Comment by kesterlester** [comment]
Actually, the sub plot labelled (a) in the last figure pasted is a variant of the thing I called (a) in the last posting. So actually reproducing (a) would be fun.

**Comment by tpgillam** [comment]
:-) I should add that the examples would (ideally) not have any dependencies beyond numpy, so relying on an external MC generator would be suboptimal. But maybe there exists a very lightweight generator that is already nicely packaged for python that could be used?

**Comment by kesterlester** [comment]
If I remember correctly, the screengrabbed plots generated in the paper shown were not generated using an external MC. It would have (most probably) have been a toy MC I wrote in a few lines. ...

**Comment by kesterlester** [comment]
> If I remember correctly, the screengrabbed plots generated in the paper shown were not generated using an external MC. It would have (most probably) have been a toy MC I wrote in a few lines. ...
> […](#)

OK - my memory was wrong about this.  BUT, creating a one-liner toy MC could still be done.  We might need to get you to complete your python stream canvas, though, so that we have a histogramming package to do the histogramming! ;)

**Comment by tpgillam** [comment]
Ah - I should have said that I think it is ok for the examples to additionally depend on matplotlib :-) [There may be a way of expressing an "examples only" dependency, but if not then people who are used to the python ecosystem will be able to fix the missing dependency very easily, since it is a very widely known and used packge]

**Comment by tpgillam** [comment]
Marking this as done, now that we have the notebook refactoring of your example: https://github.com/tpgillam/mt2/blob/master/examples/mc.ipynb
