### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by tpgillam** [tpgillam/mt2#15]
Currently only testing up to 3.8, but at some point should verify that it works on 3.9 too.

**Comment by kesterlester** [comment]
I got it to compile on 3.9 yesterday.  You can mark this as "done", at least for now, so far as I am concerned.

**Comment by tpgillam** [comment]
Thanks! I will do so once I have CI set up for 3.9, which should be easy.

**Comment by tpgillam** [comment]
Added, e.g. can be seen (currently queued) in the v0.1.6 tag run here: https://travis-ci.org/github/tpgillam/mt2/builds/758603653
