### ISSUE TITLE
CI site not aware of numpy dependency

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#18]
![](https://user-images.githubusercontent.com/2091838/107632933-1f6f1a80-6c5f-11eb-9f1c-3e31bd53a097.png)

**Comment by tpgillam** [comment]
setup.py requires numpy to be installed. This needs to be expressed in a `pyproject.toml`, and then ensure that it's included in `MANIFEST.in`

**Comment by tpgillam** [comment]
What is this pertaining to?

**Comment by tpgillam** [comment]
This should (hopefully!) be fixed by https://github.com/tpgillam/mt2/commit/71f2914660420fe81edfaf500440240a1bdecaa0

**Comment by tpgillam** [comment]
CI build now passing
