### ISSUE TITLE
Support both `const long*` and `long*` form of ufunc inner loop

### ISSUE THREAD

**Issue by tpgillam** [tpgillam/mt2#21]
At some point numpy has changed the API for ufunc declaration - ideally we want to support both, and also reflect the version requirements in our dependency structure.

**Comment by tpgillam** [comment]
https://github.com/tpgillam/mt2/issues/22#issuecomment-777406349 Has information for reproducing.

**Comment by tpgillam** [comment]
Should be fixed in https://github.com/tpgillam/mt2/commit/b326b7c5e435ee543133424466f599124d0f67d9

@kesterlester if you pull and try to build, is it fixed for you with numpy 1.18.5?

**Comment by kesterlester** [comment]
@tpgillam it worked for me.

**Comment by tpgillam** [comment]
Great!
