### ISSUE TITLE
numpy version mismatch?

### ISSUE THREAD

**Issue by tpgillam** [tpgillam/mt2#26]
Failure here: https://travis-ci.org/github/tpgillam/mt2/jobs/758603656

```
ImportError while importing test module '/home/travis/build/tpgillam/mt2/tests/test_mt2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_mt2.py:7: in <module>
    from mt2 import mt2
mt2/__init__.py:6: in <module>
    from _mt2 import mt2_ufunc
E   ImportError: numpy.core.multiarray failed to import
------------------------------- Captured stderr --------------------------------
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

**Comment by tpgillam** [comment]
It looks like the github actions are building with numpy `1.20`. If in a fresh venv I try to run the pypi manylinux wheel for mt2 0.1.6 with an older version of numpy, in this case `1.19.2`, then I see the API version mismatch exception as above.

**Comment by kesterlester** [comment]
Too complicated for me to understand, I'm afraid! :(

**Comment by tpgillam** [comment]
From here: https://numpy.org/doc/stable/reference/c-api/array.html#checking-the-api-version

"If you want to supported many different numpy versions with one extension binary, you have to build your extension with the lowest NPY_FEATURE_VERSION as possible."

**Comment by tpgillam** [comment]
This seems useful: https://pypi.org/project/oldest-supported-numpy/

**Comment by tpgillam** [comment]
And scikit-learn seem to have a good example of using it: https://github.com/scikit-learn/scikit-learn

**Comment by tpgillam** [comment]
Fixed in https://github.com/tpgillam/mt2/commit/1fa60f74815e0e06760a15effa444ef2de7d0899
