### ISSUE TITLE
Check it runs on the pyboard under micropython

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#28]

**Comment by kesterlester** [comment]
Needs https://github.com/v923z/micropython-ulab

**Comment by kesterlester** [comment]
https://micropython-ulab.readthedocs.io/en/latest/ulab-programming.html. is relevant

**Comment by kesterlester** [comment]
Micropython libs seem to have a strong philosophy that "if a library can be implemented in python (rather than C) then it should be".   One is allowed to break this rule, but only with special permission.

**Comment by tpgillam** [comment]
That sounds like a good reason to not attempt this! Might I suggest closing this?

**Comment by kesterlester** [comment]
Investigation of how micropython libraries work shows that what is effectively required, to allow it to run there, is either (a) for the mt2 calc to be done in pure python, or (b) an entirely special package be written which compiled against various parts of the micropython internal ecosystem.  In either case that's a different project than the one we have here.  So the question posed in this issue turns out to be not answerable within the scope of the project.
