### ISSUE TITLE
Surprising test comparison outcome

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#33]
There is a line in a new test which I created which sets a tolerance in the approx-equal command.  Docs say that the default tolerance is 1e-6, but the MT2 calculator should be able to do better in this test, so I pushed it up to 1e-12 and the test still passes.  However if I push this tolerance up to 1e-13 then the test fails (on my laptop -- I don't know if it fails on github or elsewhere at 1e-13).  This I fund surprising as the printouts suggest that python thinks the numbers it is comparing agree to at least 1e-15 or maybe even higher, **EVEN WHEN IT SAYS THE COMPARISON FAILS**.  This means that something fishy is happening which should be understood.

_Originally posted by @kesterlester in https://github.com/tpgillam/mt2/issues/32#issuecomment-778696362_

**Comment by kesterlester** [comment]
A "refer to this in a new issue" button generated the crazy title of this issue. Mea non culpa!

**Comment by tpgillam** [comment]
> A "refer to this in a new issue" button generated the crazy title of this issue. Mea non culpa!

I was able to rename the issue quite easily - do you have the ability to do that?

**Comment by tpgillam** [comment]
(Incidentally, I think conventionally one wouldn’t start an issue for a pull request which hasn’t been merged. Since if there is a problem with a pull request then the appropriate place to discuss it is on there)

**Comment by tpgillam** [comment]
Closing on basis of observation above.
