### ISSUE TITLE
Lally's alg should be in the test suite.

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#35]
Ask Tom nicely if he can FOR USE IN THE TEST-SUITE ONLY -- NOT IN THE PUBLIC LIBRARY -- give https://arxiv.org/src/1509.01831v2/anc/mt2_Lallyver2.h some python bindings so that we can create tests that compare our MT2 values to those it produces.  This implementation need not be a fancy ufunc thing -- just anything that "works".

**Comment by tpgillam** [comment]
I'm happy to do this. Is Colin on github? Else, can you ask if he would mind me including (with appropriate acknowledgement ofc.) his code in the repository?

**Comment by tpgillam** [comment]
[A quick scan suggests that if his algorithm is already faster than yours then there is still a bit more headroom - I've spotted a few unnecessary copies I think :) ]

**Comment by tpgillam** [comment]
Done in 235ddc38ee44d10265011665e5daf3fa315c1111 . Not publicly exported (i.e. not shown in `help(mt2)`), but it *is* accessible if you do `from mt2 import mt2_lally`

**Comment by tpgillam** [comment]
Just to note that I wrote a trivial (and maybe worthless) benchmark:

    rm -rf build/* && python setup.py build_ext -i test && PYTHONPATH=. python examples/benchmark_lester_v_lally.py
