### ISSUE TITLE
Decide whether to fix small bug in Lally code ..

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#37]
Copied here, for the record, are the code-related bits of my discussion with Lally about a potential bug in his imp:

Lally's reply:

> OK, bottom line is it looks like an error. I would have to have been thinking of something overly complicated to have put an assignment like this in an If statement. So I'm pretty sure it should have been a simple comparison.
> 
> The good news (and the reason I guess why I never picked up on it) is that, as far as I can see, it has no material effect. Just to quickly explain, even though I knew I had to watch out for the Newton-Raphson finding either higher-than-lowest-value roots, or getting caught in a local minimum, I still wanted to at least be able to output what would normally be a new, lower, upperbound from this function, which could then be used in the Regula Falsi function instead of the kinematic upperbound i.e. to gain some value / speed from going through the Newton-Raphson method first, even if it didn't actually find the correct root. What this bit of the code is doing is selecting a suitable new upperbound from the last few iterations. What the error does is pretty much ALWAYS (because x1 and xNR are unlikely to be both zero valued and so the If statement will always be true) increase the second-to-last iterated value a little (rather than only increase it if it is EQUAL to the final iterated value). This has the potential (in practice very rarely) to output a slightly higher new upperbound than would have been the case without the error, but the effect on the speed of the Regula Falsi function will be de minimis as the higher upperbound is not going to be that much higher than the next lower iterated value as we are in a local minimum type situation.
> 
> Anyway, it's a good spot! I presume it was spotted more from a 'forensic' reading of my code i.e. it just 'looked wrong' given the If statement seemed to only require a simple comparison, and not because the overall algorithm was doing something wrong? If this isn't the case I would need to look in more detail, as maybe I was actually trying to do something fancy (unlikely!).
> 

The above followed my message to him:

> I have a question about your MT2 implementation from your most recent paper. My question relates to line 421. You can see line 421 by going to the link below and scrolling down far enough.
> 
> https://github.com/tpgillam/mt2/commit/a1148d69aa5e3381cf7a0301b0b4f42f6142d2a3#diff-be879a9f457b24439e1e1e360f477a90c04c7734a61de906c28589dd25f86da1
> 
> The line in question says:
> 
> ![PastedGraphic-1](https://user-images.githubusercontent.com/2091838/108194602-ba0fa380-710e-11eb-9d97-475126362be8.png)
> 
> and I am querying why it says:
> 
> 	if (xNR = x1) {
> 
> rather than
> 
> 	if (xNR == x1) {
> 
> Both are valid C and either could (potentially) be what you want … I’ve not yet figured out … however they have different effects.  The first version assigns x1 to xNR and then passes the test if xNR is non zero, while the second version passes the test if xNR is equal to x1.
> 
> As I’ve said, it might be that you want to do the former, as written, in which case there is no bug. But if you wanted to do the latter then there is a bug.

**Comment by tpgillam** [comment]
Can Colin be persuaded to join in here? :-)

Not sure if I mentioned before, but actually the compiler spotted it! (Since this has historically been a fairly common source of bugs in general)

**Comment by tpgillam** [comment]
In this case I'll fix the code; it'll remove a compiler warning which won't hurt :-)
