### ISSUE TITLE
Show copyright message only on installation

### ISSUE THREAD

**Issue by tpgillam** [tpgillam/mt2#4]
* mt2 version: 0.1.4
* Python version: N/A
* Operating System: N/A

### Description

Currently we show a copyright message for every invocation of the mt2 root finding. We would prefer it if the message was shown once on installation, and not thereafter.

This will ideally require forking the header file from the versions available on arxiv, if you don't object @kesterlester ? (Alternatively I can make do with the existing API, but there'll be a small amount of overhead for doing so that we could otherwise avoid)

On that topic, as my basis I'll be using "v4" from arxiv, since this doesn't have the various inlining optimisations removed. No ROOT shall be used here!

**Comment by kesterlester** [comment]
Fine to use the v4.  If you want to make a v7 that could go on the arxiv and which disables the copyright message at compile time (e.g. through the use of a #defined variable  (e.g. BUILDING_FOR_PYPI ) then I could make that an official v7 on the web, that is usable by you here unchanged (albeit you define BUILDING_FOR_PYPI in your C++ config).

**Comment by tpgillam** [comment]
Possibly, though people may find it confusing that v7 reverts the inlining changes you make with respect to v6. Trying to do versioning via arxiv seems pretty non-standard, I must say! I think I would rather explicitly declare this version to be a fork of v4, then we can modify from there and track history separately.

**Comment by kesterlester** [comment]
OK - fine.

**Comment by kesterlester** [comment]
I could put all the inline things back in, though, in such a way that the same BUILDING_FOR_PYPI thing enables them, while mere mortals don't get them.

**Comment by tpgillam** [comment]
Constants could work. I'd suggest two separate constants:

`KNOBBLE_FOR_ROOT`: which disables the inlining optimisations. [Or if needed, you could call it ENABLE_INLINING if you think the default should be to play nicely with ROOT]
`DISABLE_COYPRIGHT_PRINTING`: which when set would completely remove the copyright-printing code.

That way your code remains agnostic to python, which I think would be preferable.

**Comment by kesterlester** [comment]
I will do that.

**Comment by kesterlester** [comment]
Please find attached a proposed "v7" for the arxiv.  If you agree it is acceptable I will remove the "v7" and make an arxiv submission of it.

[lester_mt2_bisect-v7.h.zip](https://github.com/tpgillam/mt2/files/5960156/lester_mt2_bisect-v7.h.zip)

(annoyingly it is zipped as github wouldn't accept it as raw .h)

**Comment by kesterlester** [comment]
PS - I should warn you that I've not actually tried to compile it ... I just presume I typed it right ...

**Comment by tpgillam** [comment]
OK, I'll give it a go - alternatively you could submit a pull request to add the file to the src/ folder

**Comment by kesterlester** [comment]
Pull request for v7 file should be with you now.

**Comment by kesterlester** [comment]
I put another in, with some small tweaks.  No plans for any more today.

**Comment by tpgillam** [comment]
I believe you sent a pull request to put the necessary copyright messages into the README. I am compiling your code with the necessary flag to prevent copyright notices being displayed in runtime, so think this is done.
