### ISSUE TITLE
Decide how to approach absolute tolerance

### ISSUE THREAD

**Issue by Rupt** [tpgillam/mt2#42]
Decide on an approach to absolute tolerance in bisection termination.

`mt2_bisect_impl` has a hard coded absolute tolerance of the type epsilon (ie min x st 1 + x > 1).

This would be unhelpful for exa-electron volt users (ANITA?).

Setting it to 0 might (as far as I know) cause infinite loops when mt2 is denormal.

I suggest the following change:
```diff
    auto epsilon = std::numeric_limits<T>::epsilon();
    auto rel_tol = epsilon < precision ? precision : epsilon;
-    auto abs_tol = epsilon;
+    auto abs_tol = std::numeric_limits<T>::min();
```

**Comment by tpgillam** [comment]
Naively I'd agree that setting the absolute tolerance to zero seems unwise... although beyond that my experience with the floating point spec is pretty limited! Maybe @kesterlester has opinions though?

My only suggestion would be whether we could write some tests that would show up the differences first, before deciding on the most appropriate course of action?

**Comment by kesterlester** [comment]
Doesn't my orgininal code have a scale pre-normalisation step?  I.e. one where a scale is determined from the inputs, then divided out of the intputs, so that the MT2 calc takes place in a unitless all-numbers-order-1-if-not-order-0 environment, with the scale then multipled back at the far end?
If not, then it certainly could work that way - and many calculators I've made in the past do work that way. If it did, then the Exa/Atto users should not be concerned.

**Comment by kesterlester** [comment]
But that last comment is separate from how to achieve better INNATE tolerances, which really need algorithms which are inherently more numerically safe.
E.g. the elipse overlap tests require many large numbers to be multiplied and added and that causes most of the inherent unavoidable of loss of precision.  Ultimately the naive/dumb  min(max(MT,MT)) def is arguably the one that is least sensitive to such issues (though having issues of its own, such as slowness and non-parabolicity in the minimum ....) but it does suggest that IF one really wanted to purse actual top best ever precision, one would probably combine an approach like the bisecion algorithm for getting (to get you very close to the final answer) with a slower but numerically more precise method (to polish your final answer to a high chrome mirror finish).

**Comment by tpgillam** [comment]
None from me, will leave to @kesterlester to decide whether this can be closed.

**Comment by kesterlester** [comment]
I’ve not tried to compile or test, but I’ve read through the diffs, and this looks like the sort of scale invariance I had in mind — and appears to be implemented well.

**Comment by tpgillam** [comment]
Excellent! I will close :-)
